# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aLzhxVqngYPcEqLkGxMaqUprin0uAybw
"""

import streamlit as st
import joblib
import pandas as pd
import os

# --- Configuration ---
MODEL_PATH = 'trained_model.joblib'

# MUST match the columns the model was trained on
FEATURE_NAMES = [
    'Unnamed: 0',
    'TV',
    'Radio',
    'Newspaper'
]
# ---------------------

# --- Model Loading Function with Compatibility Fixes ---
@st.cache_resource
def load_model(path):
    """Loads the joblib model file with compatibility fixes for scikit-learn versions."""
    if not os.path.exists(path):
        st.error(f"Error: Model file not found at '{path}'. Please ensure '{MODEL_PATH}' is in the same directory.")
        return None

    # --- START OF SCALING/VERSION COMPATIBILITY FIXES ---

    # Fix 1: Addresses 'Can't get attribute '_RemainderColsList''
    try:
        from sklearn.compose import _column_transformer
        if not hasattr(_column_transformer, '_RemainderColsList'):
            class _RemainderColsList(list):
                pass
            setattr(_column_transformer, '_RemainderColsList', _RemainderColsList)
            st.warning("Applied scikit-learn compatibility fix 1/2 for missing attribute.")
    except ImportError:
        pass

    # Fix 2: Addresses 'SimpleImputer' object has no attribute '_fill_dtype'
    try:
        from sklearn.impute import _base
        from sklearn.impute import SimpleImputer
        if not hasattr(SimpleImputer, '_fill_dtype'):
            # The attribute is used internally during loading; setting it to None works.
            setattr(SimpleImputer, '_fill_dtype', None)
            st.warning("Applied scikit-learn compatibility fix 2/2 for missing attribute.")
    except ImportError:
        pass

    # --- END OF COMPATIBILITY FIXES ---

    try:
        # joblib.load() is called after the fixes are applied
        model = joblib.load(path)
        return model
    except Exception as e:
        st.error(f"Error loading the model: {e}")
        st.caption("If issues persist, consider updating your scikit-learn package to a version closer to where the model was trained (e.g., v1.4 or newer).")
        return None


# Load the model
model = load_model(MODEL_PATH)

# --- Streamlit App Layout ---
st.set_page_config(page_title="Sales Prediction App", layout="centered")

st.title("💰 Sales Prediction Model Deployment")
st.markdown("Enter the advertising spending across different media channels to predict sales.")

if model is not None:
    # --- Input Feature Collection ---
    st.header("Input Features (Advertising Spend)")

    input_data = {}
    col1, col2 = st.columns(2)

    with col1:
        input_data['TV'] = st.number_input(
            label="TV Ad Spend ($)",
            min_value=0.0,
            value=150.0,
            step=1.0
        )
        input_data['Newspaper'] = st.number_input(
            label="Newspaper Ad Spend ($)",
            min_value=0.0,
            value=25.0,
            step=1.0
        )

    with col2:
        input_data['Radio'] = st.number_input(
            label="Radio Ad Spend ($)",
            min_value=0.0,
            value=30.0,
            step=1.0
        )
        # We set 'Unnamed: 0' to 0 as it's typically an index column, not a user input
        input_data['Unnamed: 0'] = 0


    # --- Prediction Button and Logic ---
    if st.button("Predict Sales", type="primary"):
        try:
            # 1. Convert inputs to a DataFrame
            input_df = pd.DataFrame([input_data])

            # Ensure the column names and order match the model's expectations exactly
            input_df = input_df[FEATURE_NAMES]

            # 2. Make the prediction
            prediction = model.predict(input_df)

            predicted_sales = prediction[0]

            # 3. Display the result
            st.success("---")
            st.metric(
                label="Predicted Sales (Y Variable)",
                value=f"${predicted_sales:,.2f}"
            )
            st.balloons()

        except Exception as e:
            st.error(f"An error occurred during prediction: {e}")
            st.caption("If the error is related to feature shape or naming, check the `FEATURE_NAMES` list at the top of the script.")

else:
    st.warning("Prediction cannot be performed because the model failed to load.")

# --- Customization Note ---
st.sidebar.markdown(
    """
    **✅ Status:** All known scikit-learn version and missing column errors have been addressed. The app should now load and predict correctly, assuming no other incompatibility issues exist.
    """
)