# -*- coding: utf-8 -*-
"""Untitled29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p_lKIjwx_x7EcZrxiKJ6k7MqIYogZFo4
"""

import streamlit as st
import joblib
import pandas as pd
import os

# --- Configuration ---
MODEL_PATH = 'trained_model.joblib'

# 1. FIXED: MUST match the columns the model was trained on
FEATURE_NAMES = [
    'Unnamed: 0', # Often a dummy index column
    'TV',         # Feature 1
    'Radio',      # Feature 2
    'Newspaper'   # Feature 3
]
# ---------------------

# --- Model Loading Function with Compatibility Fix ---
@st.cache_resource
def load_model(path):
    """Loads the joblib model file with compatibility fix."""
    if not os.path.exists(path):
        st.error(f"Error: Model file not found at '{path}'. Please ensure '{MODEL_PATH}' is in the same directory.")
        return None

    # Fix for 'Can't get attribute '_RemainderColsList'' error
    try:
        from sklearn.compose import _column_transformer
        if not hasattr(_column_transformer, '_RemainderColsList'):
            class _RemainderColsList(list):
                pass
            setattr(_column_transformer, '_RemainderColsList', _RemainderColsList)
    except ImportError:
        pass

    try:
        model = joblib.load(path)
        return model
    except Exception as e:
        st.error(f"Error loading the model: {e}")
        st.caption("If the error is still a missing attribute, consider updating scikit-learn.")
        return None


# Load the model
model = load_model(MODEL_PATH)

# --- Streamlit App Layout ---
st.set_page_config(page_title="Sales Prediction App", layout="centered")

st.title("💰 Sales Prediction Model Deployment")
st.markdown("Enter the advertising spending across different media channels to predict sales.")

if model is not None:
    # --- Input Feature Collection ---
    st.header("Input Features (Advertising Spend)")

    # Dictionary to store user inputs
    input_data = {}

    col1, col2 = st.columns(2)

    with col1:
        # 2. FIXED: Collecting input for TV, Radio, and Newspaper
        input_data['TV'] = st.number_input(
            label="TV Ad Spend ($)",
            min_value=0.0,
            value=150.0,
            step=1.0
        )
        input_data['Newspaper'] = st.number_input(
            label="Newspaper Ad Spend ($)",
            min_value=0.0,
            value=25.0,
            step=1.0
        )

    with col2:
        input_data['Radio'] = st.number_input(
            label="Radio Ad Spend ($)",
            min_value=0.0,
            value=30.0,
            step=1.0
        )
        # 3. FIXED: Adding the required but non-input feature
        # We set 'Unnamed: 0' to 0 as it's typically an index column
        input_data['Unnamed: 0'] = 0


    # --- Prediction Button and Logic ---
    if st.button("Predict Sales", type="primary"):
        try:
            # 1. Convert inputs to a DataFrame
            input_df = pd.DataFrame([input_data])

            # Ensure the column names and order match the model's expectations exactly
            input_df = input_df[FEATURE_NAMES]

            # 2. Make the prediction
            prediction = model.predict(input_df)

            # The prediction result might be an array, so we take the first element
            predicted_sales = prediction[0]

            # 3. Display the result
            st.success("---")
            st.metric(
                label="Predicted Sales (Y Variable)",
                value=f"${predicted_sales:,.2f}"
            )
            st.balloons()

        except Exception as e:
            st.error(f"An error occurred during prediction: {e}")
            st.caption("Please double-check that your model was trained ONLY on the four columns listed in `FEATURE_NAMES`.")

else:
    st.warning("Prediction cannot be performed because the model failed to load.")

# --- Customization Note ---
st.sidebar.markdown(
    """
    **✅ Status:** The model loading error and the missing column error are now addressed based on the error messages received.

    If you get a different error, it may indicate your model requires additional columns that were not listed in the error, or that the feature scaling/transformation pipeline in the model is causing issues.
    """
)