# -*- coding: utf-8 -*-
"""Untitled27.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wWiCM_WHJPpDV9kpdC3MKjuFRCt14Oxh
"""

import streamlit as st
import joblib
import pandas as pd
import os

# --- Configuration ---
MODEL_PATH = 'trained_model.joblib'
# IMPORTANT: Replace these with the EXACT feature names your model was trained on.
# The order also matters if your model uses positional feature input (e.g., a simple array).
# It's safest to keep them in the same order as your training data columns.
FEATURE_NAMES = [
    'Advertising_Spend',
    'Price_of_Product',
    'Store_Size_sq_ft',
    'Competition_Index'
]
# ---------------------

# --- Model Loading Function ---
@st.cache_resource
def load_model(path):
    """Loads the joblib model file."""
    if not os.path.exists(path):
        st.error(f"Error: Model file not found at '{path}'. Please ensure '{MODEL_PATH}' is in the same directory.")
        return None
    try:
        model = joblib.load(path)
        return model
    except Exception as e:
        st.error(f"Error loading the model: {e}")
        return None

# Load the model
model = load_model(MODEL_PATH)

# --- Streamlit App Layout ---
st.set_page_config(page_title="Sales Prediction App", layout="centered")

st.title("💰 Sales Prediction Model Deployment")
st.markdown("Use the controls below to input the feature values and predict the total sales.")

if model is not None:
    # --- Input Feature Collection ---
    st.header("Input Features")

    # Dictionary to store user inputs
    input_data = {}

    # Helper to create customized input fields for each feature
    col1, col2 = st.columns(2)

    # Use placeholder values, user should adjust min/max/default based on their data
    with col1:
        input_data['Advertising_Spend'] = st.number_input(
            label="Advertising Spend (e.g., $)",
            min_value=0.0,
            value=500.0,
            step=10.0
        )
        input_data['Store_Size_sq_ft'] = st.number_input(
            label="Store Size (sq ft)",
            min_value=100.0,
            value=2500.0,
            step=100.0
        )

    with col2:
        input_data['Price_of_Product'] = st.number_input(
            label="Product Price ($)",
            min_value=1.0,
            value=19.99,
            step=0.1
        )
        input_data['Competition_Index'] = st.slider(
            label="Competition Index (1=Low, 10=High)",
            min_value=1,
            max_value=10,
            value=5,
            step=1
        )

    # --- Prediction Button and Logic ---
    if st.button("Predict Sales", type="primary"):
        try:
            # 1. Convert inputs to a DataFrame
            # Ensure the DataFrame column names and order match the FEATURE_NAMES list
            input_df = pd.DataFrame([input_data])
            input_df = input_df[FEATURE_NAMES] # Reorder to match model expectations

            # 2. Make the prediction
            prediction = model.predict(input_df)

            # The prediction result might be an array, so we take the first element
            predicted_sales = prediction[0]

            # 3. Display the result
            st.success("---")
            st.metric(
                label="Predicted Sales (Y Variable)",
                value=f"${predicted_sales:,.2f}"
            )
            st.balloons()

        except Exception as e:
            st.error(f"An error occurred during prediction. Check if your model expects the correct features: {e}")

else:
    st.warning("Prediction cannot be performed because the model failed to load.")

# --- Customization Note ---
st.sidebar.markdown(
    """
    **🛠️ Customization Required:**

    1. **Replace `FEATURE_NAMES`**: Update the list at the top of the script with the exact column names your model expects.
    2. **Update Input Fields**: Modify the `st.number_input` and `st.slider` calls to match the number, type, and typical range of your actual features.
    """
)